### PR TITLE
Add Libre Space Foundation's ksc docker image

### PR DESCRIPTION
**Pull request by DL4PD**
Signed-off-by: Patrick Dohmen <dl4pd@darc.de>

### CODE REVIEW

**Comment by KOLANICH** [comment]
1. The stuff is under AGPL. Please add a badge warning about it.
2. It may make sense to add https://gitlab.com/librespacefoundation/satnogs/satnogs-decoders too.

**Comment by cshields** [comment]
is a badge really necessary?  In that case, the page links to repositories with no license provided (therefore no permission to use).. should they be flagged?

**Comment by KOLANICH** [comment]
>In that case, the page links to repositories with no license provided (therefore no permission to use).. should they be flagged?

Of course they should be. For GH repos one can use `shields.io`. For non-gh lepos they can be used too, but one has to create a badge manually. Also take a note that in some repos licenses are not in their usual places and some licenses, for example BSD ones are not recognized by GitHub correctly.

**Comment by cugu** [comment]
Thanks @DL4PD

**Pull request merged**
